In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split,KFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
pressure = pd.read_csv('./Datasets Archive/pressure.csv')
pressure = pressure['Toronto']
pressure.head()

0       NaN
1    1012.0
2    1011.0
3    1011.0
4    1010.0
Name: Toronto, dtype: float64

In [4]:
humidity = pd.read_csv('./Datasets Archive/humidity.csv')
humidity = humidity['Toronto']
humidity.head()

0     NaN
1    82.0
2    81.0
3    79.0
4    77.0
Name: Toronto, dtype: float64

In [5]:
temperature = pd.read_csv('./Datasets Archive/temperature.csv')
temperature = temperature['Toronto']
temperature.head()

0           NaN
1    286.260000
2    286.262541
3    286.269518
4    286.276496
Name: Toronto, dtype: float64

In [6]:
wind_direction = pd.read_csv('./Datasets Archive/wind_direction.csv')
wind_direction = wind_direction['Toronto']
wind_direction.head()

0      NaN
1    240.0
2    236.0
3    226.0
4    216.0
Name: Toronto, dtype: float64

In [7]:
wind_speed = pd.read_csv('./Datasets Archive/wind_speed.csv')
wind_speed = wind_speed['Toronto']
wind_speed.head()

0    NaN
1    3.0
2    3.0
3    3.0
4    3.0
Name: Toronto, dtype: float64

In [8]:
datetime = pd.read_csv('./Datasets Archive/humidity.csv')
datetime = pd.to_datetime(datetime['datetime'])
hour = datetime.dt.hour
month = datetime.dt.month
hour.head() , month.head()

(0    12
 1    13
 2    14
 3    15
 4    16
 Name: datetime, dtype: int32,
 0    10
 1    10
 2    10
 3    10
 4    10
 Name: datetime, dtype: int32)

In [9]:
df = pd.DataFrame({
                'month':month,
                'hour':hour,
                'pressure':pressure,
                'humidity':humidity,
                'wind_direction':wind_direction,
                'wind_speed':wind_speed
})
df.head()

   month  hour  pressure  humidity  wind_direction  wind_speed
0     10    12       NaN       NaN             NaN         NaN
1     10    13    1012.0      82.0           240.0         3.0
2     10    14    1011.0      81.0           236.0         3.0
3     10    15    1011.0      79.0           226.0         3.0
4     10    16    1010.0      77.0           216.0         3.0

In [10]:
y = np.array(temperature)
y[:5]

array([         nan, 286.26      , 286.26254096, 286.26951842,
       286.27649588])

In [11]:
for feature in df:
    df[feature] = df[feature].replace(0,None)
    mean_value = np.mean(df[feature])
    df[feature] = df[feature].fillna(mean_value)
df.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_12320\4214086424.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[feature] = df[feature].fillna(mean_value)

   month  hour     pressure   humidity  wind_direction  wind_speed
0     10  12.0  1018.274435  76.361909      204.537665    3.990102
1     10  13.0  1012.000000  82.000000      240.000000    3.000000
2     10  14.0  1011.000000  81.000000      236.000000    3.000000
3     10  15.0  1011.000000  79.000000      226.000000    3.000000
4     10  16.0  1010.000000  77.000000      216.000000    3.000000

In [12]:
X  = np.array(df)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.8,random_state=12)

In [13]:
X_scaler = StandardScaler()

X_train = X_scaler.fit_transform(X_train)
X_test = X_scaler.transform(X_test)

In [15]:
k = 10
k_fold = KFold(k,random_state=12,shuffle=True)
folds_error = []

KNN_model = KNeighborsClassifier(15)

for fold, (train_index,validate_index) in enumerate(k_fold.split(X_train)):
    X_train_here = X_train[train_index]
    y_train_here = y_train[train_index]

    KNN_model.fit(X_train_here,y_train_here)

    X_validate = X_train[validate_index]
    y_validate = y_train[validate_index]

    folds_error.append(KNN_model.score(X_validate))

print(np.mean(folds_error))

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.